Traceback (most recent call last):
  File "/gscratch/users/asalaberria009/env/p39-cu115/lib/python3.9/site-packages/transformers/configuration_utils.py", line 595, in _get_config_dict
    resolved_config_file = cached_path(
  File "/gscratch/users/asalaberria009/env/p39-cu115/lib/python3.9/site-packages/transformers/file_utils.py", line 1947, in cached_path
    output_path = get_from_cache(
  File "/gscratch/users/asalaberria009/env/p39-cu115/lib/python3.9/site-packages/transformers/file_utils.py", line 2151, in get_from_cache
    _raise_for_status(r)
  File "/gscratch/users/asalaberria009/env/p39-cu115/lib/python3.9/site-packages/transformers/file_utils.py", line 2078, in _raise_for_status
    request.raise_for_status()
  File "/gscratch/users/asalaberria009/env/p39-cu115/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/resolve/main/config.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gaueko0/users/ietxarri010/GrAL_Irene/erantzunak_berridatzi.py", line 130, in <module>
    main()
  File "/gaueko0/users/ietxarri010/GrAL_Irene/erantzunak_berridatzi.py", line 86, in main
    pipeline = transformers.pipeline(
  File "/gscratch/users/asalaberria009/env/p39-cu115/lib/python3.9/site-packages/transformers/pipelines/__init__.py", line 542, in pipeline
    config = AutoConfig.from_pretrained(model, revision=revision, _from_pipeline=task, **model_kwargs)
  File "/gscratch/users/asalaberria009/env/p39-cu115/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 647, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/gscratch/users/asalaberria009/env/p39-cu115/lib/python3.9/site-packages/transformers/configuration_utils.py", line 547, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/gscratch/users/asalaberria009/env/p39-cu115/lib/python3.9/site-packages/transformers/configuration_utils.py", line 624, in _get_config_dict
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co/' to load this model and it looks like meta-llama/Meta-Llama-3.1-8B-Instruct is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
srun: error: localhost: task 0: Exited with exit code 1
